[build]
  command = "npx honkit build"
  publish = "_book"

[build.environment]
  NODE_VERSION = "18"

# Remove SPA-style redirect
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200 