[build]
  publish = "docs"
  command = "node build-docs.js"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    
[[headers]]
  for = "/styles/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect domain aliases to primary domain
[[redirects]]
  from = "https://macro-browser-docs.netlify.app/*"
  to = "https://docs.macro.io/:splat"
  status = 301
  force = true 